version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yml
  
sphinx:
  builder: html
  configuration: docs/conf.py  # This should point to your conf.py

python:
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .  